import type { Metadata } from "next";
import { ImageComponent } from "../components/ImageComponent";
import "./globals.css";
import "../style/fonts.css";

export const metadata: Metadata = {
  title: "Slider-with-pagination",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex items-center justify-between w-full p-4 border border-gray-300">
          <div className="flex items-center gap-4">
            <ImageComponent
              src="/logoHeader/logo-big.svg"
              alt="STEMPS"
              width={28}
              height={28}
            />
            <p className="hidden sm:block">STEMPS</p>
          </div>
          <div className="hidden sm:flex items-center gap-6 ">
            <nav className="cursor-pointer">О школе</nav>
            <nav className="cursor-pointer">Курсы</nav>
            <nav className="cursor-pointer">Библиотека</nav>
          </div>
          <div className="flex items-center gap-4">
            <button className="hidden sm:block">Вход</button>
            <ImageComponent
              src="/logoHeader/back.svg"
              alt="STEMPS"
              width={28}
              height={28}
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
